services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  backend:
    build: ./Backend
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
    context: ./Frontend
    dockerfile: src/Dockerfile
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - backend
