- name: SSH into EC2 and deploy
  uses: appleboy/ssh-action@v0.1.10
  with:
    host: ${{ secrets.EC2_HOST }}
    username: ${{ secrets.EC2_USER }}
    key: ${{ secrets.EC2_SSH_KEY }}
    script: |
      cd ~/todo-app || git clone https://github.com/YOUR_USERNAME/YOUR_REPO.git todo-app && cd todo-app
      git pull origin main

      # Determine correct Docker Compose command
      if command -v docker-compose &> /dev/null; then
        DC="docker-compose"
      elif docker compose version &> /dev/null; then
        DC="docker compose"
      else
        echo "❌ Docker Compose is not installed"
        exit 1
      fi

      # Use the detected Docker Compose command
      $DC down
      $DC build --no-cache
      $DC up -d
